### ISSUE TITLE
Environment variable not supported on Windows

### ISSUE THREAD

**Issue by awschristou** [aws-samples/aws-sdk-js-v3-workshop#10]
While using Windows 10 and following through exercise 1, the `AWS_JS_SDK_ID` was not handled properly, resulting in:

![image](https://user-images.githubusercontent.com/39839589/65459060-d74e1e80-de03-11e9-8795-b68b1a694c40.png)

As a workaround, I changed all instances f `$AWS_JS_SDK_ID` in package.json

**Comment by trivikr** [comment]
Solution to unblock you:
Replace `$AWS_JS_SDK_ID` with the ID you plan to use in the commands of package.json

For example:
```diff
-"package": "sam package --output-template-file packaged.yaml --s3-bucket $AWS_JS_SDK_ID",
+"package": "sam package --output-template-file packaged.yaml --s3-bucket <YOUR_ID>",
```

**Comment by trivikr** [comment]
Closing as we no longer use Environment variables after moving Cloud infrastructure setup to CDK

Refs: https://github.com/aws-samples/aws-sdk-js-v3-workshop/pull/179
