### ISSUE TITLE
Table was created in us-east-1 in backend

### ISSUE THREAD

**Issue by ckkrishn** [aws-samples/aws-sdk-js-v3-workshop#12]
**Describe the bug**
Table in DDB gets created in us-east-1 and end point is directed to same:
"https://yst42vcc94.execute-api.us-east-1.amazonaws.com/"
but not able to see contents in browser.

**To Reproduce**
Follow Exercise-1 steps.

**Expected behavior**
Able to view contents in same regions as in config.

**Comment by trivikr** [comment]
Can you switch to `us-west-2`?
The value `us-west-2` was hardcoded in a working solution at some places, and we were not able to remove it.

**Comment by trivikr** [comment]
The DynamoDB table is now created using CDK, which uses default region from AWS Config.
The backend code also uses default region from AWS Config.

Refs: https://github.com/aws-samples/aws-sdk-js-v3-workshop/pull/179
