### ISSUE TITLE
Getting following error when trying to use `PutItemCommand`

### ISSUE THREAD

**Issue by c2tarun** [aws-samples/aws-sdk-js-v3-workshop#14]
**Describe the bug**
Getting following error when trying to use `PutItemCommand`
```
Argument of type 'PutItemCommand' is not assignable to parameter of type 'Command<InputTypesUnion, PutItemInput, OutputTypesUnion, PutItemOutput, DynamoDBResolvedConfiguration, Readable>'.
  Property 'model' is missing in type 'PutItemCommand' but required in type 'Command<InputTypesUnion, PutItemInput, OutputTypesUnion, PutItemOutput, DynamoDBResolvedConfiguration, Readable>'.ts(2345)
command.d.ts(28, 14): 'model' is declared here.
```

**To Reproduce**
Follow steps [here](https://github.com/aws-samples/aws-sdk-js-v3-workshop/tree/master/Exercise1/backend#reduce-bundle-size-even-more-by-just-importing-specific-commands-in-v3)

**Comment by klaytaybai** [comment]
Updated instructions are in the README.  Instead of yarn add @aws-sdk/client-dynamodb-node, use `yarn add @aws-sdk/client-dynamodb-node@preview`.

**Comment by trivikr** [comment]
This issue is caused because of some typings issue in SDK v3:
* Added a fix in README to add `// @ts-ignore` in https://github.com/aws-samples/aws-sdk-js-v3-workshop/commit/e98724ff40d67b9f37348a3678e789443befa10c
* Existing issue to track fix in v3 https://github.com/aws/aws-sdk-js-v3/issues/363
