### ISSUE TITLE
Exercise 1 yarn describe not working on Windows

### ISSUE THREAD

**Issue by awschristou** [aws-samples/aws-sdk-js-v3-workshop#15]
Using Windows 10, when I type `yarn describe` in exercise 1 I get the following:

![image](https://user-images.githubusercontent.com/39839589/65462141-036c9e00-de0a-11e9-9c3e-b06a1993d034.png)

**Comment by klaytaybai** [comment]
Thanks.  Please try adding double quotes around the query content within the package.json scripts.

**Comment by awschristou** [comment]
Thank you -- this was successful:
```
    "describe": "aws cloudformation describe-stacks --stack-name cc2-aws-js-sdk-v3-workshop --query \"Stacks[].Outputs[?OutputKey==`NotesApi`][OutputValue]\"",
```

**Comment by trivikr** [comment]
Adding `\"` doesn't work on macOS, as it throws following error:
```
Bad value for --query Stacks[].Outputs[?OutputKey==][OutputValue]: invalid token: Parse error at column 29, token "]" (RBRACKET), for expression:
"Stacks[].Outputs[?OutputKey==][OutputValue]"
```

We should move away from AWS CLI, and explore CDK

**Comment by trivikr** [comment]
Tagged this issue to explore CDK for setting up infrastructure

**Comment by trivikr** [comment]
Resolving as yarn describe is no longer required after moving to AWS CDK
Refs: https://github.com/aws-samples/aws-sdk-js-v3-workshop/pull/179
