### ISSUE TITLE
Cannot find module '@aws-sdk/util-create-request'. Cannot find module '@aws-sdk/s3-request-presigner'.

### ISSUE THREAD

**Issue by LASkuma** [aws-samples/aws-sdk-js-v3-workshop#16]
**Describe the bug**
In `getObjectUrl.ts`, throws error on [Exercise 1, frontend](https://github.com/aws-samples/aws-sdk-js-v3-workshop/blob/master/Exercise1/frontend/README.md#reduce-bundle-size-further-by-using-client-from-v3)

**To Reproduce**
1. Run `yarn add @aws-sdk/client-s3-browser@preview @aws-sdk/credential-provider-cognito-identity@preview @aws-sdk/client-cognito-identity-browser@preview` in terminal
2. Modify file according to the [instruction](https://github.com/aws-samples/aws-sdk-js-v3-workshop/blob/master/Exercise1/frontend/README.md#reduce-bundle-size-further-by-using-client-from-v3)

**Expected behavior**
No error should be thrown

**Comment by trivikr** [comment]
Hi @LASkuma, did you perform `yarn add @aws-sdk/util-create-request@preview @aws-sdk/s3-request-presigner @aws-crypto/sha256-browser@preview @aws-sdk/util-format-url@preview` which were given before the diff for `getObjectURL.ts`?

**Comment by trivikr** [comment]
Closing as:
* the question is answered in https://github.com/aws-samples/aws-sdk-js-v3-workshop/issues/16#issuecomment-534392334
* instructions were made more clear in https://github.com/aws-samples/aws-sdk-js-v3-workshop/commit/9a41fa9b885b82cebff503958d9653293204a1a5

Please comment/reopen if you have any questions.
