### ISSUE TITLE
Exercise1/backend/README.md: lambda functions not found after yarn deploy

### ISSUE THREAD

**Issue by ti2ger92** [aws-samples/aws-sdk-js-v3-workshop#18]
While attempting to follow the guide in README.md for Exercise1 backend, I arrived at the section which said: Examine initial bundle size of lambda functions. I looked in the link for Lambda functions and did not find any at all. It is possible this is because I did something wrong.

**Comment by trivikr** [comment]
Did you perform `yarn clean` before examining bundle size of lambda functions?
If yes, that's probably related to #17 which was fixed in https://github.com/aws-samples/aws-sdk-js-v3-workshop/commit/fb49e9abb21d00631269686cb6390fd60478ad9b

**Comment by trivikr** [comment]
Closing as https://github.com/aws-samples/aws-sdk-js-v3-workshop/issues/18#issuecomment-534391506 have answered the question up to my knowledge.
Please comment/reopen if you have any questions.
