### ISSUE TITLE
Redme instructions are not very clear

### ISSUE THREAD

**Issue by vinaysinghbww** [aws-samples/aws-sdk-js-v3-workshop#19]
**Describe the bug**
When I am following the instructions in redme, it is not clear on backend redme till how long we should go and in frontend redme when to start.

**To Reproduce**
1. Go to main redme
2. Click on backend redme
3. When to jump to front redme is not clear

**Expected behavior**
Clear instructions for how long we should follow backend redme, the frontend and backend redme can be done in parellel.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS
 - Browser Chrome
 - Version latest

**Comment by trivikr** [comment]
Thanks @vinaysinghbww for the suggestion.
The backend and frontend are independent, and can be worked on in parallel.
