### ISSUE TITLE
Not getting the list of identity-pools while running yarn identity-pools

### ISSUE THREAD

**Issue by vinaysinghbww** [aws-samples/aws-sdk-js-v3-workshop#20]
**Describe the bug**
While following the instructions mentioned in frontend redme of exercise 1, when I reached to execute the command to yarn identity-pools, it shows the identity-pool as empty array.

**To Reproduce**
1. Go to frontend redme of exercise 1
2. Follow the instructions
3. While executing yarn identity-pools, it shows the empty list

**Expected behavior**
Instructions should be clear to find the right data.

**Desktop (please complete the following information):**
 - OS: ios
 - Browser Chrome
 - Version Latest

**Additional context**
yarn run v1.17.3
$ aws cognito-identity list-identity-pools --max-results 20
{
    "IdentityPools": []
}
✨  Done in 1.24s.

**Comment by trivikr** [comment]
The identity pools are created by the cloud formation stack (in `yarn deploy`)
Did `yarn deploy` fail? If not, can you visit [CloudFormation](https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2) and confirm that your stack was created?

**Comment by trivikr** [comment]
@vinaysinghbww Any updates to questions raised in https://github.com/aws-samples/aws-sdk-js-v3-workshop/issues/20#issuecomment-534386460

**Comment by trivikr** [comment]
Issue no longer exists as the action in `yarn identity-pools` is now automated using CDK.
Refs: https://github.com/aws-samples/aws-sdk-js-v3-workshop/pull/179
