### ISSUE TITLE
Show how to use S3 GetObjectCommand

### ISSUE THREAD

**Issue by igilham** [aws-samples/aws-sdk-js-v3-workshop#255]
**Is your feature request related to a problem? Please describe.**

The usage of `GetObject` has changed significantly in the new SDK version 3. It is no longer easy to get the response body.

v2:
```typescript
const client = new S3({ region: 'eu-west-1' })
const data = await client.getObject({
  BucketName: 'my-bucket',
  Key: '/foo.txt',
}).promise()

// gets a string
console.log(data.Body.toString('utf-8'))
```

v3:
```typescript
const client = new S3Client({ region: 'eu-west-1' })
const cmd = new GetObjectCommand({})
const data = await client.send(cmd)

// Body is a complex object containing network primitives etc. but no body
console.log(JSON.stringify(Object.keys(data.Body)))
```

**Describe the solution you'd like**

It's not clear if the SDK's current behaviour is intentional, but for this repository it would be most useful to include a use of the `GetObjectCommand`.

**Describe alternatives you've considered**

I've been listing out the contents of `Body` from the response and attempting to read from the socket etc. but have not yet been able to read the string that comes back from S3.

**Additional context**

`Object.keys(response.Body)` returns the following:

```javascript
[
  "_readableState",
  "readable",
  "_events",
  "_eventsCount",
  "_maxListeners",
  "socket",
  "connection",
  "httpVersionMajor",
  "httpVersionMinor",
  "httpVersion",
  "complete",
  "headers",
  "rawHeaders",
  "trailers",
  "rawTrailers",
  "aborted",
  "upgrade",
  "url",
  "method",
  "statusCode",
  "statusMessage",
  "client",
  "_consuming",
  "_dumped",
  "req"
]
```

**Comment by trivikr** [comment]
Closing as this guidance query was answered in aws-sdk-js-v3 repo https://github.com/aws/aws-sdk-js-v3/issues/1877
