### ISSUE TITLE
Exercise 2 Solutions

### ISSUE THREAD

**Issue by GerardKetuma** [aws-samples/aws-sdk-js-v3-workshop#256]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Will like to see solutions for Exercise 2.

**Describe alternatives you've considered**
Just want to see alternate solutions to the suggested questions in exercise 2.

**Additional context**
None

**Comment by trivikr** [comment]
Exercise 2 solutions are being implemented in https://github.com/aws-samples/aws-sdk-js-notes-app

For example, here is an implementation of real-time audio transcription via Amazon Transcribe https://github.com/aws-samples/aws-sdk-js-notes-app/pull/7
