### ISSUE TITLE
deleteObject command not found

### ISSUE THREAD

**Issue by idkjs** [aws-samples/aws-sdk-js-v3-workshop#29]
**Describe the bug**
Looks like you didnt handle `deleteObject` in `Exercise1` readme steps.

After doing all the updates in the front end you get this error:
```
Property 'deleteObject' does not exist on type 'S3Client'.ts(2339)
```

Looks like you have to move this to `Exercise1` if its intended that `Exercise1` compile at the end of the steps in its `README.me`
https://github.com/aws-samples/aws-sdk-js-v3-workshop/blob/70d92d0f98364ae4dc1a5b094ec68537da7fbb59/Exercise2/frontend/src/libs/deleteObject.ts#L1-L13

**Comment by trivikr** [comment]
Following up in PR https://github.com/aws-samples/aws-sdk-js-v3-workshop/pull/30#issuecomment-536718999
